# Developed by: Tianyun Xuan
# Reorder Waymo open dataset to Kitti format
# --------------------------------------------------------------------

# General parameters
debug: False
# number of frames for training, -1 uses all frames
num_frames: -1
# normalize/scale the difference with corresponding range value
normalize: True
# use the last n frame to calculate the difference image
num_last_n: 2

# Inputs
type: "Falcon"
# the folder of source data
input_folder: 'data/falcon'

# Outputs
# the suffix should be the same as num_last_n!
output_folder: 'data/falcon/sequences'
visualize: True

# range image parameters
range_image:
  height: 64
  width: 2048
  fov_up: 15
  fov_down: 15
  fov_horizontal: 120
  max_range: 300
  min_range: 2.0