name: "waymo"
labels: 
  0 : TYPE_UNDEFINED
  1 : TYPE_CAR
  2 : TYPE_TRUCK
  3 : TYPE_BUS     
  4 : TYPE_OTHER_VEHICLE # Other small vehicles (e.g. pedicab) and large vehicles (e.g. construction vehicles, RV, limo, tram).
  5 : TYPE_MOTORCYCLIST
  6 : TYPE_BICYCLIST
  7 : TYPE_PEDESTRIAN
  8 : TYPE_SIGN
  9 : TYPE_TRAFFIC_LIGHT
  10: TYPE_POLE # Lamp post, traffic sign pole etc.
  11: TYPE_CONSTRUCTION_CONE # Construction cone/pole.
  12: TYPE_BICYCLE
  13: TYPE_MOTORCYCLE
  14: TYPE_BUILDING
  15: TYPE_VEGETATION # Bushes, tree branches, tall grasses, flowers etc.
  16: TYPE_TREE_TRUNK
  17: TYPE_CURB # Curb on the edge of roads. This does not include road boundaries if there’s no curb.
  18: TYPE_ROAD # Surface a vehicle could drive on. This include the driveway connecting parking lot and road over a section of sidewalk.
  19: TYPE_LANE_MARKER # Marking on the road that’s specifically for defining lanes such as single/double white/yellow lines.
  20: TYPE_OTHER_GROUND # Marking on the road other than lane markers, bumps, cateyes, railtracks etc.
  21: TYPE_WALKABLE # Most horizontal surface that’s not drivable, e.g. grassy hill,pedestrian walkway stairs etc.
  22: TYPE_SIDEWALK # Nicely paved walkable surface when pedestrians most likely to walk on.
  31: MOVING      # lidar-mos moving
  32: STATIC      # lidar-mos stat
color_map: # bgr
  0: [0, 0, 0]
  1: [245, 150, 100]
  2: [245, 230, 100]
  3: [250, 80, 100]
  4: [150, 60, 30]
  5: [255, 0, 0]
  6: [180, 30, 80]
  7: [255, 0, 0]
  8: [30, 30, 255]
  9: [200, 40, 255]
  10: [90, 30, 150]
  11: [255, 0, 255]
  12: [255, 150, 255]
  13: [75, 0, 75]
  14: [75, 0, 175]
  15: [0, 200, 255]
  16: [50, 120, 255]
  17: [0, 150, 255]
  18: [170, 255, 150]
  19: [0, 175, 0]
  20: [0, 60, 135]
  21: [80, 240, 150]
  22: [150, 240, 255]
  31: [0, 0, 255]  # lidar-mos moving
  32: [255, 0, 0]    # lidar-mos static
content: # as a ratio with the total number of points
  0: 6.32052376e-03
  1: 8.96972519e-02
  2: 8.19469528e-03
  3: 4.52027593e-03
  4: 3.19756983e-03 
  5: 0.00000000e+00
  6: 9.58140024e-05
  7: 7.73504338e-03
  8: 4.85191212e-03
  9: 2.23622941e-04
  10: 9.28619998e-03
  11: 1.56064091e-04
  12: 4.02206649e-05
  13: 1.90872856e-04
  14: 3.36115493e-01
  15: 1.89229553e-01
  16: 1.24207418e-02
  17: 8.81170581e-03
  18: 1.97868015e-01
  19: 5.16248506e-03
  20: 5.24969576e-03
  21: 5.89964876e-02
  22: 5.16357553e-02
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 0
  1 : 1
  2 : 1
  3 : 1
  4 : 1
  5 : 1
  6 : 1
  7 : 1
  8 : 2
  9 : 2
  10: 2
  11: 2
  12: 1
  13: 1
  14: 2
  15: 2
  16: 2
  17: 2
  18: 2
  19: 2
  20: 2
  21: 2
  22: 2
learning_map_inv: # inverse of previous map
  0: 0     # unlabel
  1: 31    # "moving"   
  2: 32    # "static"

learning_ignore: # Ignore classes
    0 : True # TYPE_UNDEFINED
    1 : False # TYPE_CAR
    2 : False # TYPE_TRUCK
    3 : False # TYPE_BUS     
    4 : False # TYPE_OTHER_VEHICLE
    5 : False # TYPE_MOTORCYCLIST
    6 : False # TYPE_BICYCLIST
    7 : False # TYPE_PEDESTRIAN
    8 : False # TYPE_SIGN
    9 : False # TYPE_TRAFFIC_LIGHT
    10: False # TYPE_POLE
    11: False # TYPE_CONSTRUCTION_CONE
    12: False # TYPE_BICYCLE
    13: False # TYPE_MOTORCYCLE
    14: False # TYPE_BUILDING
    15: False # TYPE_VEGETATION
    16: False # TYPE_TREE_TRUNK
    17: False # TYPE_CURB
    18: False # TYPE_ROAD
    19: False # TYPE_LANE_MARKER
    20: False # TYPE_OTHER_GROUND
    21: False # TYPE_WALKABLE
    22: False # TYPE_SIDEWALK 
  
split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
  valid:
    - 16
  test:
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
